export const endpoints = {
  login: "api/auth/user/login",
  signup: "api/auth/user/register",
  product: "api/product",
  category: "api/category",
  service: "api/service",
  cart: "api/cart",
  product_by_id: "api/product",
  address: "api/address",
  coupon: "api/coupon",
  order: "api/order",
  contact: "api/contact",
  blogs: "api/blog",
  reviews: "api/review",
  ordermy: "api/order/history",
  home: "api/home",
  distrubtors: "api/auth/user/role",
  service_page: "api/service-page",
  header: "api/header",
  internal_page: "api/internal",
  payment: "api/payment/create-session",
  cashfreeOrderDetails: "api/payment/details",
  distributors: "api/auth/user/role",
  inventoryCheck: "api/inventory/check",
};
